kproximate:
  config:
    kpNodeCores: 2
    kpNodeMemory: 2048
    kpNodeNamePrefix: kp-node
    kpNodeTemplateName: kproximate-template
    loadHeadroom: 0.2
    maxKpNodes: 4
    pmUrl: https://<proxmox-host>:8006/api2/json
    pmUserID: kproximate@pam!kproximate

  secrets:
    pmToken: <proxmox-api-token>
    rabbitmqPassword: <set-rabbitmq-password-here>
    sshKey: <ssh-public-key>
